### ISSUE TITLE
Missing reference to jest-matcher-utils

### ISSUE THREAD

**Issue by rotu** [R-js/blasjs#16]
This package seems to fail when run under `pnpm it`, seemingly due to a missing dependency on `jest-matcher-utils` referred to from `jest-extension.ts`. Attempted to fix in #15, but perhaps the type import should be removed instead.

```
 FAIL  lib/l3/complex/csyrk/__test__/test.ts
  ● Test suite failed to run

    lib/packages/__test__/jest-extension.ts:4:41 - error TS2307: Cannot find module 'jest-matcher-utils' or its corresponding type declarations.

    4 import type { MatcherHintOptions } from 'jest-matcher-utils';
```

> Do you want to contribute on webgpu or wasm versions? Create an issue and lets discuss.

_Originally posted by @jacobbogers in https://github.com/R-js/blasjs/issues/15#issuecomment-1494934964_

**Comment by jacobbogers** [comment]
Hi @rotu 

It seems this is not needed anymore, was an artifact from older version of jest, I removed the dependency and there was no difference..  let me know how it works for you using `pnpm`

Note: only `npm run test` and `npm run lint` script target works on this branch, after 3 or more kernels have been ported t to  wasm and webgpu will circle round and make an initial web bundle build.

**Comment by jacobbogers** [comment]
resolved
