### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by neuhausi** [R-js/blasjs#9]
Hi Jacob,
I came across your library and I couldn’t find a couple of functions in the library.
dposv
dpotrs
dorgqr
dgeqrf
Are you still interested in developing this library? I would be happy to fund the functions I need.
Regards,
Isaac
P.S. BTW, the library is really awesome!

**Comment by jacobbogers** [comment]
Hi @neuhausi 

Sorry for the late reply 

I am super happy you like the blasjs library and find it very usefull.

The functions _dposv,dpotrs,dorgqr,dgeqrf_  are from LAPACK library, this repo is the BLAS numerical library. I Was considering developing LAPACK, it has close to 2000 kernel functions (BLAS has 100 orso subroutines)

I have reached out to you (your website https://www.canvasxpress.org/)

Best Regards
Jacob Bogers
